[package]
name = "agda-mode"
version = "0.1.0"
authors = ["ice1000 <ice1000kotlin@foxmail.com>"]
edition = "2018"
license = "Apache-2.0"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
clap = { version = "2.33.0", optional = true }
structopt = { version = "0.3", optional = true }
rustyline = { version = "5.0.0", optional = true }
minitt-util = { version = "0.1.1", features = ["cli", "repl"], optional = true }

[features]
default = ["cli"]
cli = ["clap", "structopt", "rustyline", "minitt-util"]

[lib]
name = "nar"
path = "src/lib.rs"

[[bin]]
name = "narc"
path = "src/cli/mod.rs"
required-features = ["cli"]
