[package]
name = "agda-mode"
version = "0.0.2"
authors = ["ice1000 <ice1000kotlin@foxmail.com>"]
description = "Accessing Agda's interaction mode via command line, in Rust"
edition = "2018"
license = "Apache-2.0"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio-process = "0.3.0-alpha"

[workspace]
members = ["agda-tac"]
