[package]
name = "agda-mode"
version = "0.0.1"
authors = ["ice1000 <ice1000kotlin@foxmail.com>"]
description = "Accessing Agda's interaction mode via command line, in Rust"
edition = "2018"
license = "Apache-2.0"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "2.33", optional = true }
structopt = { version = "0.3", optional = true }
minitt-util = { version = "0.1", features = ["cli"], optional = true }
tokio = { version = "0.2.0-alpha", default-features = false, features = ["io", "rt-full", "codec"] }
tokio-process = "0.3.0-alpha"
futures-util = "0.3"

[features]
default = ["cli"]
cli = ["clap", "structopt", "minitt-util"]

[lib]
name = "agda_mode"
path = "src/lib.rs"

[[bin]]
name = "agda-tac"
path = "src/cli/mod.rs"
required-features = ["cli"]
