name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # TODO: stable
        rust: [nightly]

    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Build agda-mode
      run: cargo build --release --verbose
    - name: Run agda-mode tests
      run: cargo test --release --verbose
    - name: Build agda-tac
      run: cargo build -p agda-tac --release --verbose
    - name: Run agda-tac tests
      run: cargo test -p agda-tac --release --verbose

    - uses: actions/upload-artifact@master
      with:
        name: agda-tac
        path: target/release/agda-tac
